### ISSUE TITLE
[완료] 주제 선정, 온라인 응원법 사이트 만들기.

### ISSUE THREAD

**Issue by koremp** [CodeSoom/project-react-2-koremp#1]
아이디어가 없다!

**Comment by koremp** [comment]
1. K-POP 가수들의 노래의 응원법을 팬들의 목소리를 녹음해서 합치는 사이트
2. Youtube에 있는 수많은 노래 - 가사 싱크 영상들 관련된 사이트 (자동 생성?)
3. 피아노, 클래식 등의 사이트에서 악보와 싱크되는 사이트

**Comment by koremp** [comment]
4. 사회적 이슈 관련 가시화 사이트
    * 낙태, N번방 등 여성 관련 정책
5. 스포츠 관련 사이트
    * 현재 이적시장인 롤 리그의 이적/영입 관련 정보를 메일로 보내주는 서비스
    * 이적/영입 관련 정보를 사이트로 보여주기
    * 선수들로 팀 꾸리는 간단한 놀이? (lol fm)
6. 자동 닉네임 생성 사이트?
    * 키워드를 선택하여 관련 단어들로 닉네임 생성해주기..?
7. 위스키, 칵테일 등 술 관련 사이트
    * 구입 가능한 곳, 칵테일 바 정리된 곳 (like awesome-alcohol-things ?)
    * 홈텐딩 하려는 사람들에게 추천하는 도구/주류 등을 정리하는? 
8. 악플 고소 사이트
    * 악플 고소하는 방법 정리
    * 악플러들의 댓글을 pdf로 처리해주는 서비스
    * 연예, 스포츠 관련 댓글을 막을 정도로 이슈가 되었던 일이라 마음이 간다.

**Comment by hannut91** [comment]
아이디어가 엄청 많으시네요 ㅎㅎㅎ 도균님이 가장 사용하고 싶은 걸 만드는게 좋을 것 같아요

**Comment by hannut91** [comment]
어떤걸로 고르셨나요?

**Comment by koremp** [comment]
9. 약물에 대한 정보 쉽게 접근할 수 있는 사이트
    * 정신과를 다니며 약물에 대한 정보에 대한 접근이 불편함을 깨달음
    * 정리된 사이트가 있으면 좋겠음
10. 각종 혐오/가짜뉴스 관련된 거짓 증명 사이트

**Comment by koremp** [comment]
현재 컴백한 비투비의 응원법 영상을 보고 팬데믹 시국인 비대면과 온라인을 함께하여 떼창을 할 수 있는, 1번 주제로 선정했습니다.
