### ISSUE TITLE
응원 음성 녹음 기능 구현하기

### ISSUE THREAD

**Issue by koremp** [CodeSoom/project-react-2-koremp#12]
마이크로 사용자가 응원을 녹음하고, 다시 확인할 수 있는 기능을 구현해야 합니다.

**Comment by Kihyun92** [comment]
좋습니다! 이번주 일요일에는 가능하면 최소한의 서비스를 이용할 수 있게 되면 좋겠네요 :)

**Comment by koremp** [comment]
1차 버전에서는 응원 방법만 보여주기
