### ISSUE TITLE
이번 주차에 할 일을 이슈업 해주세요~

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-2-koremp#14]
4주차에는 어떤 작업을 진행할 것인지, 사용자에게 어떤 가치를 전달할 수 있을지 작성해주세요.

그리고 앞으로 방향도 한번 고민해보시고 남은 할일들을 리스트업 해보시면 좋을 것 같습니다 😁

**Comment by koremp** [comment]
알겠습니다!
