### ISSUE TITLE
계획을 작성해주세요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-koremp#2]
1. 이 앱을 언제 사용하나요?
2. 제약 조건은 무엇인가요?
3. 구체적인 사례는 무엇인가요?
4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.

이 템플릿에 맞춰서 작성해주세요

**Comment by koremp** [comment]
README에 계획을 업데이트했습니다.
