### ISSUE TITLE
4주차 작업 내용

### ISSUE THREAD

**Issue by koremp** [CodeSoom/project-react-2-koremp#27]

**Comment by koremp** [comment]
gh-pages를 사용하여 배포하는데 gh-pages 브랜치 설정, main.js 파일 적용 등 여러 문제가 나고 PR도 동일한 내용으로 쓸데없이 반복적으로 작성하고 있다.

**Comment by koremp** [comment]
gh-pages 관련 SPA 문서를 보다가 spa-github-pages를 번역한 [spa-github-pages-ko](https://github.com/sujinleeme/spa-github-pages-ko)를 봤는데 메인 브랜치가 아닌 마스터 브랜치로 번역되어 있었다. 2년 전 번역이니 본문의 master를 main으로 바꿔서 PR을 올렸다.

**Comment by koremp** [comment]
spa-github-pages-ko의 PR이 머지되었다

**Comment by koremp** [comment]
gh-pages 설정해서 workflows 파일을 추가했다.

**Comment by koremp** [comment]
gh-pages 브랜치 설정이 이해가 잘 안되어서 브랜치를 지우고 테스트 PR을 머지했다.

**Comment by koremp** [comment]
테스트 PR을 머지하니까 gh-pages 브랜치가 만들어지기는 했는데 dist 폴더안에 있는 index.html, 404.html이 없다. 어떻게 해결하지?

**Comment by koremp** [comment]
내 로컬에서 ```$ gh-pages -d dist```를 실행하는 것과 workflows에서 실행하는 것이 다르다. 그런데 workflows에서는 gh-pages 명령어 실행이 안되네? 뭘 어떻게 해야하는거지 ..

**Comment by koremp** [comment]
![image](https://user-images.githubusercontent.com/18482476/101672595-6b53e680-3a99-11eb-9ad7-6b27a6e1ed8c.png)

**Comment by koremp** [comment]
![image](https://user-images.githubusercontent.com/18482476/101672857-b968ea00-3a99-11eb-8e4b-b254ed984ca9.png)
actions-gh-pages 의 설명은 위와 같다.

**Comment by koremp** [comment]
![image](https://user-images.githubusercontent.com/18482476/101672982-e3baa780-3a99-11eb-968c-9dd8bc105951.png)
그리고 내 workflow는 이렇다.

**Comment by koremp** [comment]
그런데 dist 폴더 안에는 index.html과 404.html이 없다. 
매번 PR을 머지할 때마다 자동으로 workflow가 실행되고 (만약 gh-pages 브랜치가 없다면 생성함), dist 디렉토리 안의 파일들을 publish한다. 
```$ npm run build``` 명령어를 실행하면 dist/main.js가 생성되는데 github actions에서 설정해주는 것을 모르겠다. 흠...

**Comment by koremp** [comment]
github actions에서 위와 같이 설정하면 되는 것 같다. 
관련하여 workflows를 수정하여 PR, 머지했다. 
![image](https://user-images.githubusercontent.com/18482476/101674993-88d67f80-3a9c-11eb-8ddc-77b38e6be6d3.png)

**Comment by koremp** [comment]
gh-pages를 삭제했더니 github pages를 다시 설정해줘야했다.

**Comment by koremp** [comment]
![image](https://user-images.githubusercontent.com/18482476/101676907-2b8ffd80-3a9f-11eb-8b52-f32119ca238d.png)
![image](https://user-images.githubusercontent.com/18482476/101676921-32b70b80-3a9f-11eb-8076-0afe7fab9cc5.png)
위와 같이 router basename 설정 오류인 것 같은 내용들이 있다.

**Comment by koremp** [comment]
basename 설정 관련 오류는 좀 시간이 걸릴 것 같다. 일단 actions-gh-pages 를 사용하여 gh-pages 배포는 일단 성공했고, router basename 관련 문제 해결은 자고 일어난 다음에...

**Comment by koremp** [comment]
거울을 봤더니 머리카락이 흰 티셔츠에 잔뜩 붙어있다. 엉엉 ㅠㅠ 개발자의 숙명 탈모..

**Comment by Kihyun92** [comment]
아이고 제가 너무 늦게봤네요.ㅠㅠ 배포는 성공 하신것 같네요 👍🏼  basename 관련해서는 작업 중이신 것 같은데 혹시 잘 안되면 말씀해주세요!

**Comment by Kihyun92** [comment]
와우 속도가 붙으신 것 같아 너무 좋네요! 화이팅입니다 😁

**Comment by koremp** [comment]
배포에 성공했다.

**Comment by koremp** [comment]
song/:id 의 songDetail 페이지를 리팩토링 중이다.
